spring:
  application:
    name: nelsoncustomer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/nelson
    username: root
    password: zigzag
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      connection-properties: useSSL = false
server:
  port: 8082
  
debug: false
logging:
  path: /users/pawel/server/logs
  level:
    com.motivecloud.nelson: debug
